import { Express, Router } from 'express';
import { env } from '@/config/env';
import { authRoutes } from '@/modules/auth/auth.routes';
import { memberRoutes } from '@/modules/members/members.routes';
import { familyRoutes } from '@/modules/family/family.routes';
import { monkRoutes } from '@/modules/monks/monks.routes';
import { templeRoutes } from '@/modules/temples/temples.routes';
import { jainCenterRoutes } from '@/modules/jainCenters/jainCenters.routes';
import { dharamshalaRoutes } from '@/modules/dharamshalas/dharamshalas.routes';
import { staffRoutes } from '@/modules/staff/staff.routes';
import { visitorRoutes } from '@/modules/visitors/visitors.routes';
import { bookingRoutes } from '@/modules/bookings/bookings.routes';
import { donationRoutes } from '@/modules/donations/donations.routes';
import { eventRoutes } from '@/modules/events/events.routes';
import { ticketRoutes } from '@/modules/tickets/tickets.routes';
import { seatingRoutes } from '@/modules/seating/seating.routes';
import { tourRoutes } from '@/modules/tours99/tours99.routes';
import { feedRoutes } from '@/modules/feed/feed.routes';
import { offerRoutes } from '@/modules/offers/offers.routes';
import { adRoutes } from '@/modules/ads/ads.routes';
import { newsRoutes } from '@/modules/news/news.routes';
import { communityPageRoutes } from '@/modules/communityPages/communityPages.routes';
import { pollRoutes } from '@/modules/polls/polls.routes';
import { calendarRoutes } from '@/modules/calendar/calendar.routes';
import { counterRoutes } from '@/modules/counters/counters.routes';
import { trackingRoutes } from '@/modules/tracking/tracking.routes';
import { deviceRoutes } from '@/modules/devices/devices.routes';
import { alertRoutes } from '@/modules/alerts/alerts.routes';
import { communicationRoutes } from '@/modules/communication/communication.routes';
import { announcementRoutes } from '@/modules/announcements/announcements.routes';
import { galleryRoutes } from '@/modules/gallery/gallery.routes';
import { volunteerRoutes } from '@/modules/volunteers/volunteers.routes';
import { ticketsSupportRoutes } from '@/modules/ticketsSupport/ticketsSupport.routes';
import { notificationRoutes } from '@/modules/notifications/notifications.routes';
import { reportRoutes } from '@/modules/reports/reports.routes';
import { settingsRoutes } from '@/modules/settings/settings.routes';
import { auditLogRoutes } from '@/modules/auditLogs/auditLogs.routes';
import { dashboardRoutes } from '@/modules/dashboard/dashboard.routes';
import { masterDataRoutes } from '@/modules/masterData/masterData.routes';
import { searchRoutes } from '@/modules/search/search.routes';
import { uploadRoutes } from '@/modules/uploads/uploads.routes';
// New admin panel modules
import { faqRoutes } from '@/modules/faqs/faqs.routes';
import { chaturmasRoutes } from '@/modules/chaturmas/chaturmas.routes';
import { feedbackRoutes } from '@/modules/feedback/feedback.routes';
import { incorrectReportRoutes } from '@/modules/incorrectReports/incorrectReports.routes';
// Super Admin exclusive modules (Banners, Home Sections, Subscription Plans, Manual Tracking)
import { bannerRoutes } from '@/modules/banners/banners.routes';
import { homeSectionRoutes } from '@/modules/homeSections/homeSections.routes';
import { subscriptionPlanRoutes } from '@/modules/subscriptionPlans/subscriptionPlans.routes';
import { manualTrackingRoutes } from '@/modules/manualTracking/manualTracking.routes';
import { receiptRoutes } from '@/modules/receipts/receipts.routes';

export function registerRoutes(app: Express) {
  const v1 = Router();

  v1.use('/auth', authRoutes);
  v1.use('/members', memberRoutes);
  v1.use('/family', familyRoutes);
  v1.use('/monks', monkRoutes);
  v1.use('/temples', templeRoutes);
  v1.use('/jain-centers', jainCenterRoutes);
  v1.use('/dharamshalas', dharamshalaRoutes);
  v1.use('/staff', staffRoutes);
  v1.use('/visitors', visitorRoutes);
  v1.use('/bookings', bookingRoutes);
  v1.use('/donations', donationRoutes);
  v1.use('/receipts', receiptRoutes);
  v1.use('/events', eventRoutes);
  v1.use('/tickets', ticketRoutes);
  v1.use('/seating', seatingRoutes);
  v1.use('/tours', tourRoutes);
  v1.use('/feed', feedRoutes);
  v1.use('/offers', offerRoutes);
  v1.use('/ads', adRoutes);
  v1.use('/news', newsRoutes);
  v1.use('/community-pages', communityPageRoutes);
  v1.use('/polls', pollRoutes);
  v1.use('/calendar', calendarRoutes);
  v1.use('/counters', counterRoutes);
  v1.use('/tracking', trackingRoutes);
  v1.use('/devices', deviceRoutes);
  v1.use('/alerts', alertRoutes);
  v1.use('/communication', communicationRoutes);
  v1.use('/announcements', announcementRoutes);
  v1.use('/gallery', galleryRoutes);
  v1.use('/volunteers', volunteerRoutes);
  v1.use('/support-tickets', ticketsSupportRoutes);
  v1.use('/notifications', notificationRoutes);
  v1.use('/reports', reportRoutes);
  v1.use('/settings', settingsRoutes);
  v1.use('/audit-logs', auditLogRoutes);
  v1.use('/dashboard', dashboardRoutes);
  v1.use('/master-data', masterDataRoutes);
  v1.use('/search', searchRoutes);
  v1.use('/uploads', uploadRoutes);
  // New admin panel modules
  v1.use('/faqs', faqRoutes);
  v1.use('/chaturmas', chaturmasRoutes);
  v1.use('/feedback', feedbackRoutes);
  v1.use('/incorrect-reports', incorrectReportRoutes);
  // Super Admin exclusive modules
  v1.use('/banners', bannerRoutes);
  v1.use('/home-sections', homeSectionRoutes);
  v1.use('/subscription-plans', subscriptionPlanRoutes);
  v1.use('/manual-tracking', manualTrackingRoutes);

  app.use(env.API_BASE_PATH, v1);
}

