import { PrismaClient, MonkGender } from "@prisma/client";

const prisma = new PrismaClient();

async function seedMonks() {
  console.log("Starting Monk Profiles seeding (Real Data, 15 Profiles, Full Fields)...");

  // First, delete the monks we created earlier using their publicIds
  await prisma.monkProfile.deleteMany({
    where: {
      publicId: {
        in: ["JFMNK401", "JFMNK402", "JFMNK403", "JFMNK404", "JFMNK405", "JFMNK406", "JFMNK407", "JFMNK408", "JFMNK409", "JFMNK410", "JFMNK411", "JFMNK412", "JFMNK413", "JFMNK414", "JFMNK415"]
      }
    }
  });

  const monks = [
    {
      publicId: "JFMNK401",
      dikshaName: "Acharya Shri Vidyasagar Ji Maharaj",
      gender: MonkGender.SADHU,
      nameBeforeDiksha: "Vidyadhar",
      dob: new Date("1946-10-10"),
      dobPlace: "Sadalaga, Karnataka",
      dikshaDate: new Date("1968-06-30"),
      dikshaPlace: "Ajmer, Rajasthan",
      bio: "Acharya Shri Vidyasagar Ji Maharaj was one of the best known modern Digambara Jain Acharyas. He is known both for his scholarship and tap (austerity).",
      status: "NIRVANA",
      nirvanaDate: new Date("2024-02-18"),
      nirvanaPlace: "Dongargarh, Chhattisgarh",
      languages: ["Hindi", "Sanskrit", "Prakrit", "Kannada", "English"],
      socialLinks: { youtube: "https://youtube.com/vidyasagarji" },
      shortName: "Vidyasagar Ji",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d1/Acharya5.jpg",
      verified: true,
      chaturmasHistory: { current: "Dongargarh" },
      routine: { pravachan: "09:00 AM Daily", gochari: "11:30 AM", viharPreference: "Morning" },
      preDikshaFather: { name: "Shri Mallappa" },
      preDikshaMother: { name: "Shrimati Shrimati" },
      preDikshaLocation: { address: "Sadalaga, Karnataka" },
      siblings: { brother: 2, sister: 2 },
      tapasya: [{ name: "Upvas", year: "Daily Routine" }],
      health: { bloodGroup: "O+" },
      sanghContacts: { phone: "+919876543210" }
    },
    {
      publicId: "JFMNK402",
      dikshaName: "Acharya Shri Mahashraman Ji",
      gender: MonkGender.SADHU,
      nameBeforeDiksha: "Mohan Dugar",
      dob: new Date("1962-05-13"),
      dobPlace: "Sardahar, Rajasthan",
      dikshaDate: new Date("1974-05-05"),
      dikshaPlace: "Sardahar, Rajasthan",
      bio: "Acharya Shri Mahashraman Ji is the eleventh Acharya, supreme head of Jain Swetambar Terapanth sect. He leads the Ahimsa Yatra promoting non-violence.",
      status: "ACTIVE",
      languages: ["Hindi", "Rajasthani", "Sanskrit", "Prakrit"],
      socialLinks: { website: "https://ahimsayatra.org" },
      shortName: "Mahashraman Ji",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cd/Acharya_Mahashraman.jpg",
      verified: true,
      chaturmasHistory: { current: "Mumbai, Maharashtra" },
      routine: { pravachan: "08:30 AM Daily", gochari: "12:00 PM", viharPreference: "Early Morning" },
      preDikshaFather: { name: "Shri Jhumarmal Dugar" },
      preDikshaMother: { name: "Shrimati Nemakumari Dugar" },
      preDikshaLocation: { address: "Sardahar, Rajasthan" },
      siblings: { brother: 1, sister: 1 },
      tapasya: [{ name: "Varsitap", year: "2015" }],
      health: { bloodGroup: "A+" },
      sanghContacts: { phone: "+918876543211", email: "info@terapanth.com" }
    },
    {
      publicId: "JFMNK403",
      dikshaName: "Acharya Shri Tulsi",
      gender: MonkGender.SADHU,
      nameBeforeDiksha: "Tulsi Khater",
      dob: new Date("1914-10-20"),
      dobPlace: "Ladnun, Rajasthan",
      dikshaDate: new Date("1925-10-10"),
      dikshaPlace: "Ladnun, Rajasthan",
      bio: "Acharya Shri Tulsi was a prominent Jain religious leader. He was the founder of the Anuvrat movement and the Jain Vishva Bharati Institute.",
      status: "NIRVANA",
      nirvanaDate: new Date("1997-06-23"),
      nirvanaPlace: "Gangashahar, Rajasthan",
      languages: ["Hindi", "Sanskrit", "Rajasthani"],
      socialLinks: {},
      shortName: "Acharya Tulsi",
      photoUrl: null,
      verified: true,
      chaturmasHistory: { current: "Gangashahar" },
      routine: { pravachan: "09:00 AM", gochari: "11:00 AM" },
      preDikshaFather: { name: "Jhumarmal Khater" },
      preDikshaMother: { name: "Vadna Ji" },
      preDikshaLocation: { address: "Ladnun, Rajasthan" },
      siblings: { brother: 1, sister: 0 },
      tapasya: [{ name: "Kalyanak Tap", year: "1980" }],
      health: { bloodGroup: "B+" }
    },
    {
      publicId: "JFMNK404",
      dikshaName: "Acharya Shri Mahapragya Ji",
      gender: MonkGender.SADHU,
      nameBeforeDiksha: "Nathmal",
      dob: new Date("1920-06-14"),
      dobPlace: "Tamdakor, Rajasthan",
      dikshaDate: new Date("1931-01-29"),
      dikshaPlace: "Sardarshahar, Rajasthan",
      bio: "Acharya Mahapragya was the tenth head of the Svetambar Terapanth order of Jainism. He was a highly respected spiritual leader, philosopher, and creator of Preksha Meditation.",
      status: "NIRVANA",
      nirvanaDate: new Date("2010-05-09"),
      nirvanaPlace: "Sardarshahar, Rajasthan",
      languages: ["Hindi", "Sanskrit", "Prakrit"],
      socialLinks: {},
      shortName: "Mahapragya Ji",
      photoUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c9/Acharya_Mahapragya.jpg",
      verified: true,
      chaturmasHistory: { current: "Sardarshahar" },
      routine: { pravachan: "09:30 AM", gochari: "11:30 AM" },
      preDikshaFather: { name: "Tolaram Ji" },
      preDikshaMother: { name: "Balu Ji" },
      preDikshaLocation: { address: "Tamdakor, Rajasthan" },
      siblings: { brother: 0, sister: 0 },
      tapasya: [{ name: "Ayambil Vardhaman Tap", year: "2001" }],
      health: { bloodGroup: "O+" }
    },
    {
      publicId: "JFMNK405",
      dikshaName: "Rashtrasant Param Pujya Namramuni Maharaj Saheb",
      gender: MonkGender.SADHU,
      nameBeforeDiksha: "Namit",
      dob: new Date("1970-09-26"),
      dobPlace: "Nagpur, Maharashtra",
      dikshaDate: new Date("1989-11-03"),
      dikshaPlace: "Rajkot, Gujarat",
      bio: "A highly revered Jain saint of the Sthanakvasi sect, inspiring millions globally through profound discourses, humanitarian activities (Parasdham), and youth connection.",
      status: "ACTIVE",
      languages: ["Gujarati", "Hindi", "English"],
      socialLinks: { youtube: "https://youtube.com/parasdham", website: "https://parasdham.org" },
      shortName: "Namramuni Maharaj",
      photoUrl: null,
      verified: true,
      chaturmasHistory: { current: "Rajkot, Gujarat" },
      routine: { pravachan: "09:00 AM Daily", gochari: "12:00 PM", viharPreference: "Afternoon" },
      preDikshaFather: { name: "Shri Shashikantbhai" },
      preDikshaMother: { name: "Shrimati Pushpaben" },
      preDikshaLocation: { address: "Nagpur, Maharashtra" },
      siblings: { brother: 2, sister: 0 },
      tapasya: [{ name: "Siddhi Tap", year: "2020" }],
      health: { bloodGroup: "AB+" },
      sanghContacts: { phone: "+919988776655", email: "info@parasdham.org" }
    },
    {
      publicId: "JFMNK406",
      dikshaName: "Acharya Shri Ratnasundersuri Maharaj Saheb",
      gender: MonkGender.SADHU,
      nameBeforeDiksha: "Rajnikant",
      dob: new Date("1948-01-05"),
      dobPlace: "Deesa, Gujarat",
      dikshaDate: new Date("1967-01-01"),
      dikshaPlace: "Ahmedabad, Gujarat",
      bio: "A renowned Jain Acharya of the Shwetambar Murtipujak sect. He has authored over 300 books and is a highly respected social reformer and motivational speaker.",
      status: "ACTIVE",
      languages: ["Gujarati", "Hindi", "Sanskrit"],
      socialLinks: { website: "https://ratnatraya.org" },
      shortName: "Ratnasundersuri MS",
      photoUrl: null,
      verified: true,
      chaturmasHistory: { current: "Ahmedabad, Gujarat" },
      routine: { pravachan: "08:30 AM Daily" },
      preDikshaFather: { name: "Shri Dalichandbhai" },
      preDikshaMother: { name: "Shrimati Champaben" },
      preDikshaLocation: { address: "Deesa, Gujarat" },
      tapasya: [{ name: "Maaskshaman", year: "1999" }]
    },
    {
      publicId: "JFMNK407",
      dikshaName: "Gachhadhipati Acharya Shri Yugbhushan Surishwarji",
      gender: MonkGender.SADHU,
      nameBeforeDiksha: "Not specified",
      dob: new Date("1957-01-01"),
      dobPlace: "Gujarat, India",
      dikshaDate: new Date("1977-01-01"),
      dikshaPlace: "Palitana, Gujarat",
      bio: "Revered as Pandit Maharaj, he is the Gachhadhipati of the Mohanjeet Samuday, leading profound discourses on Jain Agams and philosophy.",
      status: "ACTIVE",
      languages: ["Gujarati", "Hindi", "Prakrit", "Sanskrit"],
      socialLinks: { website: "https://jyot.in" },
      shortName: "Acharya Yugbhushan Suri",
      photoUrl: null,
      verified: true,
      chaturmasHistory: { current: "Mumbai" },
      routine: { pravachan: "09:30 AM Daily" }
    },
    {
      publicId: "JFMNK408",
      dikshaName: "Muni Shri Pramansagar Ji",
      gender: MonkGender.SADHU,
      nameBeforeDiksha: "Naveen",
      dob: new Date("1967-06-27"),
      dobPlace: "Hazaribagh, Jharkhand",
      dikshaDate: new Date("1988-03-31"),
      dikshaPlace: "Sonagiri, Madhya Pradesh",
      bio: "A prominent Digambar Jain monk, disciple of Acharya Vidyasagar. Well known for his 'Shanka Samadhan' program answering life queries using Jain philosophy.",
      status: "ACTIVE",
      languages: ["Hindi", "Sanskrit"],
      socialLinks: { youtube: "https://youtube.com/pramansagar" },
      shortName: "Pramansagar Ji",
      photoUrl: null,
      verified: true,
      chaturmasHistory: { current: "Jaipur, Rajasthan" },
      routine: { pravachan: "08:00 AM Daily", gochari: "10:30 AM" },
      preDikshaFather: { name: "Shri Surendra Kumar" },
      preDikshaMother: { name: "Shrimati Shanti Devi" },
      tapasya: [{ name: "Nirjala Upvas", year: "2012" }]
    },
    {
      publicId: "JFMNK409",
      dikshaName: "Muni Shri Tarunsagar Ji Maharaj",
      gender: MonkGender.SADHU,
      nameBeforeDiksha: "Pawan Kumar Jain",
      dob: new Date("1967-06-26"),
      dobPlace: "Damoh, Madhya Pradesh",
      dikshaDate: new Date("1981-01-01"),
      dikshaPlace: "Chhattisgarh",
      bio: "An Indian Digambara monk known for his 'Kadve Pravachan' (Bitter Discourses) criticizing hypocrisy in society. He addressed various legislative assemblies.",
      status: "NIRVANA",
      nirvanaDate: new Date("2018-09-01"),
      nirvanaPlace: "Delhi",
      languages: ["Hindi"],
      socialLinks: {},
      shortName: "Tarunsagar Ji",
      photoUrl: null,
      verified: true,
      chaturmasHistory: { current: "Delhi" },
      routine: { pravachan: "09:00 AM" },
      preDikshaFather: { name: "Shri Pratap Chand" },
      preDikshaMother: { name: "Shrimati Shanti Bai" }
    },
    {
      publicId: "JFMNK410",
      dikshaName: "Acharya Shri Chandana Ji (Tai Maharaj)",
      gender: MonkGender.SADHVI,
      nameBeforeDiksha: "Shakuntala",
      dob: new Date("1937-01-26"),
      dobPlace: "Ahmednagar, Maharashtra",
      dikshaDate: new Date("1953-01-01"),
      dikshaPlace: "Palitana, Gujarat",
      bio: "The first female Jain Acharya. Founder of Veerayatan, known for exceptional humanitarian work, eye hospitals, and educational institutions in Bihar and globally.",
      status: "ACTIVE",
      languages: ["Hindi", "Marathi", "English", "Sanskrit"],
      socialLinks: { website: "https://veerayatan.org" },
      shortName: "Acharya Chandanaji",
      photoUrl: null,
      verified: true,
      chaturmasHistory: { current: "Rajgir, Bihar" },
      routine: { pravachan: "10:00 AM Daily" }
    },
    {
      publicId: "JFMNK411",
      dikshaName: "Sadhvi Shri Kanakprabha Ji",
      gender: MonkGender.SADHVI,
      nameBeforeDiksha: "Kanak",
      dob: new Date("1941-07-22"),
      dobPlace: "Ladnun, Rajasthan",
      dikshaDate: new Date("1960-07-08"),
      dikshaPlace: "Rajsamand, Rajasthan",
      bio: "She was the Mahashramani (head of the nuns) of the Swetambar Terapanth order, author of many books and an exceptional orator.",
      status: "NIRVANA",
      nirvanaDate: new Date("2022-03-17"),
      nirvanaPlace: "Delhi",
      languages: ["Hindi", "Rajasthani", "Sanskrit"],
      socialLinks: {},
      shortName: "Sadhvi Kanakprabha Ji",
      photoUrl: null,
      verified: true,
      chaturmasHistory: { current: "Delhi" },
      routine: { pravachan: "09:00 AM" }
    },
    {
      publicId: "JFMNK412",
      dikshaName: "Acharya Shri Shivmuni Ji Maharaj",
      gender: MonkGender.SADHU,
      nameBeforeDiksha: "Shiv Kumar",
      dob: new Date("1942-03-15"),
      dobPlace: "Punjab, India",
      dikshaDate: new Date("1971-05-11"),
      dikshaPlace: "Punjab",
      bio: "The current National Acharya (Shraman Sangh) of the Sthanakvasi sect. He heavily promotes Dhyan (Meditation) and Ahimsa globally.",
      status: "ACTIVE",
      languages: ["Hindi", "Punjabi", "English"],
      socialLinks: { website: "https://shramansangh.org" },
      shortName: "Acharya Shivmuni",
      photoUrl: null,
      verified: true,
      chaturmasHistory: { current: "Ludhiana, Punjab" },
      routine: { pravachan: "08:30 AM Daily" }
    },
    {
      publicId: "JFMNK413",
      dikshaName: "Muni Shri Sudhasagar Ji",
      gender: MonkGender.SADHU,
      nameBeforeDiksha: "Not specified",
      dob: new Date("1958-01-01"),
      dobPlace: "Madhya Pradesh",
      dikshaDate: new Date("1980-01-01"),
      dikshaPlace: "Madhya Pradesh",
      bio: "A highly respected Digambar monk and disciple of Acharya Vidyasagar Ji. He is instrumental in reviving ancient Jain tirths and establishing educational institutions.",
      status: "ACTIVE",
      languages: ["Hindi"],
      socialLinks: { youtube: "https://youtube.com/sudhasagarji" },
      shortName: "Sudhasagar Ji",
      photoUrl: null,
      verified: true,
      chaturmasHistory: { current: "Ajmer, Rajasthan" },
      routine: { pravachan: "08:45 AM Daily" }
    },
    {
      publicId: "JFMNK414",
      dikshaName: "Acharya Shri Ramlal Ji Maharaj Saheb",
      gender: MonkGender.SADHU,
      nameBeforeDiksha: "Ramlal",
      dob: new Date("1950-01-01"),
      dobPlace: "Rajasthan",
      dikshaDate: new Date("1970-01-01"),
      dikshaPlace: "Rajasthan",
      bio: "A prominent Acharya of the Sadhumargi Jain Shravak Sangh (Sthanakvasi). Known for his strict adherence to agams, tap, and deep spiritual discourses.",
      status: "ACTIVE",
      languages: ["Hindi", "Rajasthani"],
      socialLinks: { website: "https://sadhumargi.com" },
      shortName: "Acharya Ramlal Ji",
      photoUrl: null,
      verified: true,
      chaturmasHistory: { current: "Bikaner, Rajasthan" },
      routine: { pravachan: "09:00 AM Daily" }
    },
    {
      publicId: "JFMNK415",
      dikshaName: "Acharya Shri Vijay Vallabh Suri",
      gender: MonkGender.SADHU,
      nameBeforeDiksha: "Chhagan",
      dob: new Date("1870-10-26"),
      dobPlace: "Baroda, Gujarat",
      dikshaDate: new Date("1887-05-05"),
      dikshaPlace: "Radhanpur, Gujarat",
      bio: "A historic visionary Shwetambar Acharya who worked for the upliftment of the masses through education, establishing many Gurukuls and educational institutions.",
      status: "NIRVANA",
      nirvanaDate: new Date("1954-09-22"),
      nirvanaPlace: "Mumbai, Maharashtra",
      languages: ["Gujarati", "Hindi"],
      socialLinks: {},
      shortName: "Vallabh Suri",
      photoUrl: null,
      verified: true,
      chaturmasHistory: { current: "Mumbai" },
      routine: { pravachan: "08:00 AM" }
    }
  ];

  for (const monk of monks) {
    await prisma.monkProfile.create({
      data: monk
    });
    console.log(`Created Monk: ${monk.dikshaName}`);
  }

  console.log("Successfully seeded 15 Monk Profiles with real data, including detailed nested fields!");
}

seedMonks()
  .catch((e) => {
    console.error("Error seeding Monks:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
