import { z } from 'zod';

export const createOrganizationSchema = z.object({
  body: z.object({
    type: z.enum(['TEMPLE', 'JAIN_CENTER', 'DHARAMSHALA', 'BHOJANSHALA', 'COMMUNITY_HALL', 'TRUST_OFFICE']),
    name: z.string().min(1),
    shortName: z.string().optional(),
    trustName: z.string().optional(),
    trustRegistrationNumber: z.string().optional(),
    communityId: z.string().optional(),
    subCommunityId: z.string().optional(),
    gacchaId: z.string().optional(),
    mulNayakBhagwanId: z.string().optional(),
    mulNayakImageUrl: z.string().optional(),
    muritCount: z.number().int().optional(),
    templeType: z.enum(['SHIKHAR_BADDHA', 'GHAR_DERASAR', 'JAIN_CENTRE']).optional(),
    tithiCalendarTypeId: z.string().optional(),
    history: z.string().optional(),
    addressLine: z.string().optional(),
    city: z.string().optional(),
    state: z.string().optional(),
    country: z.string().optional(),
    pincode: z.string().optional(),
    lat: z.number().optional(),
    lng: z.number().optional(),
    googleMapsLink: z.string().optional(),
    facilities: z.array(z.string()).optional(),
    hasUpashray: z.boolean().optional(),
    upashrayLocation: z.string().optional(),
    hasEventHall: z.boolean().optional(),
    eventHallBookable: z.boolean().optional(),
    eventHallPurpose: z.string().optional(),
    eventHallBookingLink: z.string().optional(),
    eventHallBookingItemId: z.string().optional(),
    sect: z.string().optional(),
    subSect: z.string().optional(),
    gacchaName: z.string().optional(),
    preferredCurrency: z.string().optional(),
    morningStart: z.string().optional(),
    morningEnd: z.string().optional(),
    eveningStart: z.string().optional(),
    eveningEnd: z.string().optional(),
    pakshalStart: z.string().optional(),
    pakshalEnd: z.string().optional(),
    poojaStart: z.string().optional(),
    poojaEnd: z.string().optional(),
    aartiMorning: z.string().optional(),
    aartiEvening: z.string().optional(),
    dharamshalaRooms: z.string().optional(),
    dharamshalaOffice: z.string().optional(),
    dharamshalaPhone: z.string().optional(),
    dharamshalaContact: z.string().optional(),
    dharamshalaContactMemberId: z.string().optional(),
    dharamshalaOnline: z.string().optional(),
    pathshalaTimings: z.string().optional(),
    pathshalaDays: z.string().optional(),
    pathshalaTeacher: z.string().optional(),
    pathshalaTeacherMemberId: z.string().optional(),
    hasBhojanshala: z.boolean().optional(),
    bhojanshalaBreakfastCharge: z.string().optional(),
    bhojanshalaBreakfastTiming: z.string().optional(),
    bhojanshalaLunchCharge: z.string().optional(),
    bhojanshalaLunchTiming: z.string().optional(),
    bhojanshalaDinnerCharge: z.string().optional(),
    bhojanshalaDinnerTiming: z.string().optional(),
    bhojanshalaContact: z.string().optional(),
    bhojanshalaContactMemberId: z.string().optional(),
    bhojanshalaMealType: z.string().optional(),
    bhojanshalaAvailability: z.string().optional(),
    bankAccountName: z.string().optional(),
    bankAccount: z.string().optional(),
    bankIfsc: z.string().optional(),
    upiId: z.string().optional(),
    bankName: z.string().optional(),
    bankBranch: z.string().optional(),
    is80gEligible: z.boolean().optional(),
    csrEligible: z.boolean().optional(),
    donationQrUrl: z.string().optional(),
    disclaimerText: z.string().optional(),
    landmark: z.string().optional(),
    railwayStation: z.string().optional(),
    district: z.string().optional(),
    hasTempleInside: z.boolean().optional(),
    insideTempleType: z.enum(['SHIKHAR_BADDHA', 'GHAR_DERASAR']).optional(),
    templeMulNayakName: z.string().optional(),
    templeMulNayakImageUrl: z.string().optional(),
    templeTithiCalendar: z.string().optional(),
    templeOpeningHours: z.string().optional(),
    templePakshalStart: z.string().optional(),
    templePoojaStart: z.string().optional(),
    templeAartiEvening: z.string().optional(),
    checkInTime: z.string().optional(),
    checkOutTime: z.string().optional(),
    advanceBookingRequired: z.boolean().optional(),
    onlineBookingAvailable: z.boolean().optional(),
    dharamshalaStatus: z.string().optional(),
    adminBlockedRooms: z.string().optional(),
    emergencyContact: z.string().optional(),
    caretakerDetails: z.string().optional(),
    rulesText: z.string().optional(),
    primaryContactMemberId: z.string().optional(),
    secondaryContactMemberId: z.string().optional(),
    contactEmail: z.string().email().optional().or(z.literal('')),
    contactMobileVerified: z.boolean().optional(),
    contactWhatsAppVerified: z.boolean().optional(),
    contactEmailVerified: z.boolean().optional(),
    primaryContactPreference: z.string().optional(),
    donationQrCodeUrl: z.string().optional(),
    instaLink: z.string().optional(),
    facebookLink: z.string().optional(),
    youtubeLink: z.string().optional(),
    buildings: z.array(z.object({
      id: z.string(),
      name: z.string(),
      imageUrl: z.string().optional(),
      // §57: room numbers are defined once at the building level first, then
      // a room type picks which of those numbers it covers — instead of
      // free-typing a number range per room type with no shared registry.
      roomNumbers: z.array(z.string()).optional(),
      roomTypes: z.array(z.object({
        id: z.string(),
        name: z.string(),
        category: z.string().optional(),
        type: z.string(),
        roomCount: z.string().optional(),
        bedCapacity: z.string().optional(),
        charges: z.string().optional(),
        chargesType: z.string().optional(),
        deposit: z.string().optional(),
        attachedBathroom: z.string().optional(),
        amenities: z.array(z.string()).optional(),
        roomNumber: z.string().optional(),
        viewType: z.string().optional(),
        bathroomType: z.string().optional(),
        bedType: z.string().optional(),
        extraMattressCount: z.number().optional(),
        extraMattressCharge: z.number().optional(),
        images: z.array(z.string()).max(6).optional(),
      })).optional(),
    })).optional(),
  }),
});

export const updateOrganizationSchema = z.object({ body: createOrganizationSchema.shape.body.partial() });

export const addTrusteeSchema = z.object({ body: z.object({ memberId: z.string(), designation: z.string().min(1) }) });
export const addVolunteerSchema = z.object({ body: z.object({ memberId: z.string(), area: z.string().optional() }) });
export const addContactSchema = z.object({ body: z.object({ memberId: z.string(), role: z.string().optional() }) });

export const addDhajaRecordSchema = z.object({
  body: z.object({
    year: z.number().int(),
    dhajaOf: z.string().optional(),
    dhajaDate: z.coerce.date().optional(),
    descriptionEn: z.string().optional(),
    descriptionHi: z.string().optional(),
    linkedMemberIds: z.array(z.string()).optional(),
    status: z.enum(['FINALIZED', 'NOT_YET_FINALIZED', 'AVAILABLE', 'BOOKED', 'PENDING']).optional(),
  }),
});

export const addReviewSchema = z.object({ body: z.object({ rating: z.number().int().min(1).max(5), comment: z.string().optional() }) });
export const replyReviewSchema = z.object({ body: z.object({ adminReply: z.string().min(1) }) });

export const addNoticeSchema = z.object({
  body: z.object({
    title: z.string().min(1),
    body: z.string().min(1),
    isPinned: z.boolean().optional(),
    startDate: z.preprocess((val) => (val === "" || val === null ? undefined : val), z.coerce.date().optional()),
    endDate: z.preprocess((val) => (val === "" || val === null ? undefined : val), z.coerce.date().optional()),
  }),
});

export const addGalleryImageSchema = z.object({ body: z.object({ imageUrl: z.string().min(1), order: z.number().int().optional() }) });

export const reportIncorrectInfoSchema = z.object({ body: z.object({ description: z.string().min(1) }) });
